<<<<<<< HEAD
package(default_visibility = ["//tensorflow:internal"])

filegroup(
    name = "iron-ajax",
    srcs = [
        "index.html",
        "iron-ajax.html",
        "iron-request.html",
=======
# AUTOGENERATED FILE by tensorboard_bower_dependency_sync.py

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "d3",
    srcs = [
        "d3.js",
        "d3.min.js",
        "package.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-dropdown",
    srcs = [
        "index.html",
        "iron-dropdown.html",
        "iron-dropdown-scroll-manager.html",
=======
    name = "dagre",
    srcs = [
        "dist/dagre.core.js",
        "dist/dagre.core.min.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "accessibility-developer-tools",
    srcs = ["dist/js/axs_testing.js"],
)

filegroup(
    name = "iron-doc-viewer",
    srcs = [
        "index.html",
        "iron-doc-property.css",
        "iron-doc-property.html",
        "iron-doc-viewer.css",
        "iron-doc-viewer.html",
    ],
)

filegroup(
    name = "iron-icons",
    srcs = [
        "av-icons.html",
        "communication-icons.html",
        "device-icons.html",
        "editor-icons.html",
        "hardware-icons.html",
        "image-icons.html",
        "index.html",
        "iron-icons.html",
        "maps-icons.html",
        "notification-icons.html",
        "social-icons.html",
=======
    name = "es6_promise",
    srcs = [
        "promise.js",
        "promise.min.js",
    ],
)

filegroup(
    name = "font_roboto",
    srcs = ["roboto.html"],
)

filegroup(
    name = "graphlib",
    srcs = [
        "dist/graphlib.core.js",
        "dist/graphlib.core.min.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-icon-button",
    srcs = [
        "index.html",
        "paper-icon-button.html",
=======
    name = "iron_a11y_announcer",
    srcs = [
        "index.html",
        "iron-a11y-announcer.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "sinonjs",
    srcs = ["sinon.js"],
)

filegroup(
    name = "paper-dropdown-menu",
    srcs = [
        "index.html",
        "paper-dropdown-menu.html",
=======
    name = "iron_a11y_keys_behavior",
    srcs = [
        "index.html",
        "iron-a11y-keys-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-flex-layout",
    srcs = [
        "classes/iron-flex-layout.html",
        "classes/iron-shadow-flex-layout.html",
        "index.html",
        "iron-flex-layout.html",
=======
    name = "iron_ajax",
    srcs = [
        "index.html",
        "iron-ajax.html",
        "iron-request.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-autogrow-textarea",
=======
    name = "iron_autogrow_textarea",
>>>>>>> tensorflow/master
    srcs = [
        "index.html",
        "iron-autogrow-textarea.html",
    ],
)

filegroup(
<<<<<<< HEAD
    name = "d3",
    srcs = [
        "d3.js",
        "d3.min.js",
        "package.js",
=======
    name = "iron_behaviors",
    srcs = [
        "index.html",
        "iron-button-state.html",
        "iron-control-state.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-component-page",
    srcs = [
        "index.html",
        "iron-component-page.css",
        "iron-component-page.html",
=======
    name = "iron_checked_element_behavior",
    srcs = [
        "index.html",
        "iron-checked-element-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "stacky",
    srcs = [
        "gulpfile.js",
        "lib/formatting.js",
        "lib/index.js",
        "lib/normalization.js",
        "lib/parsing.js",
=======
    name = "iron_collapse",
    srcs = [
        "index.html",
        "iron-collapse.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-styles",
    srcs = [
        "classes/global.html",
        "classes/shadow.html",
        "classes/shadow-layout.html",
        "classes/typography.html",
        "color.html",
        "default-theme.html",
        "demo.css",
        "demo-pages.html",
        "index.html",
        "paper-styles.html",
        "paper-styles-classes.html",
        "shadow.html",
        "typography.html",
=======
    name = "iron_dropdown",
    srcs = [
        "index.html",
        "iron-dropdown.html",
        "iron-dropdown-scroll-manager.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-input",
    srcs = [
        "all-imports.html",
        "index.html",
        "paper-input.html",
        "paper-input-addon-behavior.html",
        "paper-input-behavior.html",
        "paper-input-char-counter.html",
        "paper-input-container.html",
        "paper-input-error.html",
        "paper-textarea.html",
=======
    name = "iron_fit_behavior",
    srcs = [
        "index.html",
        "iron-fit-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-item",
    srcs = [
        "all-imports.html",
        "index.html",
        "paper-icon-item.html",
        "paper-item.html",
        "paper-item-body.html",
        "paper-item-shared-styles.html",
=======
    name = "iron_flex_layout",
    srcs = [
        "classes/iron-flex-layout.html",
        "classes/iron-shadow-flex-layout.html",
        "index.html",
        "iron-flex-layout.html",
        "iron-flex-layout-classes.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "marked-element",
    srcs = [
        "index.html",
        "marked-element.html",
        "marked-import.html",
    ],
)

filegroup(
    name = "prism",
    srcs = [
        "components.js",
        "components/prism-abap.js",
        "components/prism-abap.min.js",
        "components/prism-actionscript.js",
        "components/prism-actionscript.min.js",
        "components/prism-apacheconf.js",
        "components/prism-apacheconf.min.js",
        "components/prism-apl.js",
        "components/prism-apl.min.js",
        "components/prism-applescript.js",
        "components/prism-applescript.min.js",
        "components/prism-asciidoc.js",
        "components/prism-asciidoc.min.js",
        "components/prism-aspnet.js",
        "components/prism-aspnet.min.js",
        "components/prism-autohotkey.js",
        "components/prism-autohotkey.min.js",
        "components/prism-autoit.js",
        "components/prism-autoit.min.js",
        "components/prism-bash.js",
        "components/prism-bash.min.js",
        "components/prism-basic.js",
        "components/prism-basic.min.js",
        "components/prism-batch.js",
        "components/prism-batch.min.js",
        "components/prism-bison.js",
        "components/prism-bison.min.js",
        "components/prism-brainfuck.js",
        "components/prism-brainfuck.min.js",
        "components/prism-c.js",
        "components/prism-c.min.js",
        "components/prism-clike.js",
        "components/prism-clike.min.js",
        "components/prism-coffeescript.js",
        "components/prism-coffeescript.min.js",
        "components/prism-core.js",
        "components/prism-core.min.js",
        "components/prism-cpp.js",
        "components/prism-cpp.min.js",
        "components/prism-crystal.js",
        "components/prism-crystal.min.js",
        "components/prism-csharp.js",
        "components/prism-csharp.min.js",
        "components/prism-css.js",
        "components/prism-css.min.js",
        "components/prism-css-extras.js",
        "components/prism-css-extras.min.js",
        "components/prism-d.js",
        "components/prism-d.min.js",
        "components/prism-dart.js",
        "components/prism-dart.min.js",
        "components/prism-diff.js",
        "components/prism-diff.min.js",
        "components/prism-docker.js",
        "components/prism-docker.min.js",
        "components/prism-eiffel.js",
        "components/prism-eiffel.min.js",
        "components/prism-elixir.js",
        "components/prism-elixir.min.js",
        "components/prism-erlang.js",
        "components/prism-erlang.min.js",
        "components/prism-fortran.js",
        "components/prism-fortran.min.js",
        "components/prism-fsharp.js",
        "components/prism-fsharp.min.js",
        "components/prism-gherkin.js",
        "components/prism-gherkin.min.js",
        "components/prism-git.js",
        "components/prism-git.min.js",
        "components/prism-glsl.js",
        "components/prism-glsl.min.js",
        "components/prism-go.js",
        "components/prism-go.min.js",
        "components/prism-groovy.js",
        "components/prism-groovy.min.js",
        "components/prism-haml.js",
        "components/prism-haml.min.js",
        "components/prism-handlebars.js",
        "components/prism-handlebars.min.js",
        "components/prism-haskell.js",
        "components/prism-haskell.min.js",
        "components/prism-haxe.js",
        "components/prism-haxe.min.js",
        "components/prism-http.js",
        "components/prism-http.min.js",
        "components/prism-icon.js",
        "components/prism-icon.min.js",
        "components/prism-inform7.js",
        "components/prism-inform7.min.js",
        "components/prism-ini.js",
        "components/prism-ini.min.js",
        "components/prism-j.js",
        "components/prism-j.min.js",
        "components/prism-jade.js",
        "components/prism-jade.min.js",
        "components/prism-java.js",
        "components/prism-java.min.js",
        "components/prism-javascript.js",
        "components/prism-javascript.min.js",
        "components/prism-jsx.js",
        "components/prism-jsx.min.js",
        "components/prism-julia.js",
        "components/prism-julia.min.js",
        "components/prism-keyman.js",
        "components/prism-keyman.min.js",
        "components/prism-kotlin.js",
        "components/prism-kotlin.min.js",
        "components/prism-latex.js",
        "components/prism-latex.min.js",
        "components/prism-less.js",
        "components/prism-less.min.js",
        "components/prism-lolcode.js",
        "components/prism-lolcode.min.js",
        "components/prism-lua.js",
        "components/prism-lua.min.js",
        "components/prism-makefile.js",
        "components/prism-makefile.min.js",
        "components/prism-markdown.js",
        "components/prism-markdown.min.js",
        "components/prism-markup.js",
        "components/prism-markup.min.js",
        "components/prism-matlab.js",
        "components/prism-matlab.min.js",
        "components/prism-mel.js",
        "components/prism-mel.min.js",
        "components/prism-mizar.js",
        "components/prism-mizar.min.js",
        "components/prism-monkey.js",
        "components/prism-monkey.min.js",
        "components/prism-nasm.js",
        "components/prism-nasm.min.js",
        "components/prism-nginx.js",
        "components/prism-nginx.min.js",
        "components/prism-nim.js",
        "components/prism-nim.min.js",
        "components/prism-nix.js",
        "components/prism-nix.min.js",
        "components/prism-nsis.js",
        "components/prism-nsis.min.js",
        "components/prism-objectivec.js",
        "components/prism-objectivec.min.js",
        "components/prism-ocaml.js",
        "components/prism-ocaml.min.js",
        "components/prism-oz.js",
        "components/prism-oz.min.js",
        "components/prism-parigp.js",
        "components/prism-parigp.min.js",
        "components/prism-parser.js",
        "components/prism-parser.min.js",
        "components/prism-pascal.js",
        "components/prism-pascal.min.js",
        "components/prism-perl.js",
        "components/prism-perl.min.js",
        "components/prism-php.js",
        "components/prism-php.min.js",
        "components/prism-php-extras.js",
        "components/prism-php-extras.min.js",
        "components/prism-powershell.js",
        "components/prism-powershell.min.js",
        "components/prism-processing.js",
        "components/prism-processing.min.js",
        "components/prism-prolog.js",
        "components/prism-prolog.min.js",
        "components/prism-puppet.js",
        "components/prism-puppet.min.js",
        "components/prism-pure.js",
        "components/prism-pure.min.js",
        "components/prism-python.js",
        "components/prism-python.min.js",
        "components/prism-q.js",
        "components/prism-q.min.js",
        "components/prism-qore.js",
        "components/prism-qore.min.js",
        "components/prism-r.js",
        "components/prism-r.min.js",
        "components/prism-rest.js",
        "components/prism-rest.min.js",
        "components/prism-rip.js",
        "components/prism-rip.min.js",
        "components/prism-roboconf.js",
        "components/prism-roboconf.min.js",
        "components/prism-ruby.js",
        "components/prism-ruby.min.js",
        "components/prism-rust.js",
        "components/prism-rust.min.js",
        "components/prism-sas.js",
        "components/prism-sas.min.js",
        "components/prism-sass.js",
        "components/prism-sass.min.js",
        "components/prism-scala.js",
        "components/prism-scala.min.js",
        "components/prism-scheme.js",
        "components/prism-scheme.min.js",
        "components/prism-scss.js",
        "components/prism-scss.min.js",
        "components/prism-smalltalk.js",
        "components/prism-smalltalk.min.js",
        "components/prism-smarty.js",
        "components/prism-smarty.min.js",
        "components/prism-sql.js",
        "components/prism-sql.min.js",
        "components/prism-stylus.js",
        "components/prism-stylus.min.js",
        "components/prism-swift.js",
        "components/prism-swift.min.js",
        "components/prism-tcl.js",
        "components/prism-tcl.min.js",
        "components/prism-textile.js",
        "components/prism-textile.min.js",
        "components/prism-twig.js",
        "components/prism-twig.min.js",
        "components/prism-typescript.js",
        "components/prism-typescript.min.js",
        "components/prism-verilog.js",
        "components/prism-verilog.min.js",
        "components/prism-vhdl.js",
        "components/prism-vhdl.min.js",
        "components/prism-vim.js",
        "components/prism-vim.min.js",
        "components/prism-wiki.js",
        "components/prism-wiki.min.js",
        "components/prism-yaml.js",
        "components/prism-yaml.min.js",
        "examples.js",
        "gulpfile.js",
        "plugins/autolinker/prism-autolinker.css",
        "plugins/autolinker/prism-autolinker.js",
        "plugins/autolinker/prism-autolinker.min.js",
        "plugins/autoloader/prism-autoloader.js",
        "plugins/autoloader/prism-autoloader.min.js",
        "plugins/file-highlight/prism-file-highlight.js",
        "plugins/file-highlight/prism-file-highlight.min.js",
        "plugins/highlight-keywords/prism-highlight-keywords.js",
        "plugins/highlight-keywords/prism-highlight-keywords.min.js",
        "plugins/ie8/prism-ie8.css",
        "plugins/ie8/prism-ie8.js",
        "plugins/ie8/prism-ie8.min.js",
        "plugins/jsonp-highlight/prism-jsonp-highlight.js",
        "plugins/jsonp-highlight/prism-jsonp-highlight.min.js",
        "plugins/keep-markup/prism-keep-markup.js",
        "plugins/keep-markup/prism-keep-markup.min.js",
        "plugins/line-highlight/prism-line-highlight.css",
        "plugins/line-highlight/prism-line-highlight.js",
        "plugins/line-highlight/prism-line-highlight.min.js",
        "plugins/line-numbers/prism-line-numbers.css",
        "plugins/line-numbers/prism-line-numbers.js",
        "plugins/line-numbers/prism-line-numbers.min.js",
        "plugins/previewer-angle/prism-previewer-angle.css",
        "plugins/previewer-angle/prism-previewer-angle.js",
        "plugins/previewer-angle/prism-previewer-angle.min.js",
        "plugins/previewer-base/prism-previewer-base.css",
        "plugins/previewer-base/prism-previewer-base.js",
        "plugins/previewer-base/prism-previewer-base.min.js",
        "plugins/previewer-color/prism-previewer-color.css",
        "plugins/previewer-color/prism-previewer-color.js",
        "plugins/previewer-color/prism-previewer-color.min.js",
        "plugins/previewer-easing/prism-previewer-easing.css",
        "plugins/previewer-easing/prism-previewer-easing.js",
        "plugins/previewer-easing/prism-previewer-easing.min.js",
        "plugins/previewer-gradient/prism-previewer-gradient.css",
        "plugins/previewer-gradient/prism-previewer-gradient.js",
        "plugins/previewer-gradient/prism-previewer-gradient.min.js",
        "plugins/previewer-time/prism-previewer-time.css",
        "plugins/previewer-time/prism-previewer-time.js",
        "plugins/previewer-time/prism-previewer-time.min.js",
        "plugins/remove-initial-line-feed/prism-remove-initial-line-feed.js",
        "plugins/remove-initial-line-feed/prism-remove-initial-line-feed.min.js",
        "plugins/show-invisibles/prism-show-invisibles.css",
        "plugins/show-invisibles/prism-show-invisibles.js",
        "plugins/show-invisibles/prism-show-invisibles.min.js",
        "plugins/show-language/prism-show-language.css",
        "plugins/show-language/prism-show-language.js",
        "plugins/show-language/prism-show-language.min.js",
        "plugins/wpd/prism-wpd.css",
        "plugins/wpd/prism-wpd.js",
        "plugins/wpd/prism-wpd.min.js",
        "prism.js",
        "tests/helper/components.js",
        "tests/helper/prism-loader.js",
        "tests/helper/test-case.js",
        "tests/helper/test-discovery.js",
        "tests/helper/token-stream-transformer.js",
        "tests/run.js",
        "tests/run-child.js",
        "tests/testrunner-tests.js",
        "themes/prism.css",
        "themes/prism-coy.css",
        "themes/prism-dark.css",
        "themes/prism-funky.css",
        "themes/prism-okaidia.css",
        "themes/prism-tomorrow.css",
        "themes/prism-twilight.css",
        "vendor/promise.js",
    ],
)

filegroup(
    name = "paper-progress",
    srcs = [
        "index.html",
        "paper-progress.html",
=======
    name = "iron_form_element_behavior",
    srcs = [
        "index.html",
        "iron-form-element-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-checked-element-behavior",
    srcs = [
        "index.html",
        "iron-checked-element-behavior.html",
=======
    name = "iron_icon",
    srcs = [
        "index.html",
        "iron-icon.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-toolbar",
    srcs = [
        "index.html",
        "paper-toolbar.html",
=======
    name = "iron_icons",
    srcs = [
        "av-icons.html",
        "communication-icons.html",
        "device-icons.html",
        "editor-icons.html",
        "hardware-icons.html",
        "image-icons.html",
        "index.html",
        "iron-icons.html",
        "maps-icons.html",
        "notification-icons.html",
        "places-icons.html",
        "social-icons.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "async",
    srcs = [
        "deps/nodeunit.css",
        "deps/nodeunit.js",
        "lib/async.js",
        "support/sync-package-managers.js",
=======
    name = "iron_iconset_svg",
    srcs = [
        "index.html",
        "iron-iconset-svg.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "es6-promise",
    srcs = [
        "promise.js",
        "promise.min.js",
=======
    name = "iron_input",
    srcs = [
        "index.html",
        "iron-input.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "promise-polyfill",
    srcs = [
        "Gruntfile.js",
        "Promise.js",
        "Promise.min.js",
        "Promise-Statics.js",
        "promise-polyfill.html",
        "promise-polyfill-lite.html",
=======
    name = "iron_list",
    srcs = [
        "index.html",
        "iron-list.html",
        "test/smoke/avg-worst-case.html",
        "test/smoke/dummy-data.html",
        "test/smoke/index.html",
        "test/smoke/physical-count.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "font-roboto",
    srcs = ["roboto.html"],
)

filegroup(
    name = "paper-menu",
    srcs = [
        "index.html",
        "paper-menu.html",
        "paper-menu-shared.css",
        "paper-submenu.html",
=======
    name = "iron_menu_behavior",
    srcs = [
        "index.html",
        "iron-menu-behavior.html",
        "iron-menubar-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-icon",
    srcs = [
        "index.html",
        "iron-icon.html",
=======
    name = "iron_meta",
    srcs = [
        "index.html",
        "iron-meta.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-meta",
    srcs = [
        "index.html",
        "iron-meta.html",
=======
    name = "iron_overlay_behavior",
    srcs = [
        "index.html",
        "iron-overlay-backdrop.html",
        "iron-overlay-behavior.html",
        "iron-overlay-manager.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "lodash",
    srcs = [
        "lodash.js",
        "lodash.min.js",
=======
    name = "iron_range_behavior",
    srcs = [
        "index.html",
        "iron-range-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-resizable-behavior",
=======
    name = "iron_resizable_behavior",
>>>>>>> tensorflow/master
    srcs = [
        "demo/src/x-app.html",
        "index.html",
        "iron-resizable-behavior.html",
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-fit-behavior",
    srcs = [
        "index.html",
        "iron-fit-behavior.html",
=======
    name = "iron_selector",
    srcs = [
        "index.html",
        "iron-multi-selectable.html",
        "iron-selectable.html",
        "iron-selection.html",
        "iron-selector.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-overlay-behavior",
    srcs = [
        "index.html",
        "iron-overlay-backdrop.html",
        "iron-overlay-behavior.html",
        "iron-overlay-manager.html",
=======
    name = "iron_validatable_behavior",
    srcs = [
        "index.html",
        "iron-validatable-behavior.html",
    ],
)

filegroup(
    name = "lodash",
    srcs = [
        "lodash.js",
        "lodash.min.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "neon-animation",
=======
    name = "neon_animation",
>>>>>>> tensorflow/master
    srcs = [
        "animations/cascaded-animation.html",
        "animations/fade-in-animation.html",
        "animations/fade-out-animation.html",
        "animations/hero-animation.html",
        "animations/opaque-animation.html",
        "animations/reverse-ripple-animation.html",
        "animations/ripple-animation.html",
        "animations/scale-down-animation.html",
        "animations/scale-up-animation.html",
        "animations/slide-down-animation.html",
<<<<<<< HEAD
        "animations/slide-from-left-animation.html",
        "animations/slide-from-right-animation.html",
=======
        "animations/slide-from-bottom-animation.html",
        "animations/slide-from-left-animation.html",
        "animations/slide-from-right-animation.html",
        "animations/slide-from-top-animation.html",
>>>>>>> tensorflow/master
        "animations/slide-left-animation.html",
        "animations/slide-right-animation.html",
        "animations/slide-up-animation.html",
        "animations/transform-animation.html",
        "demo/card/index.html",
        "demo/card/x-card.html",
        "demo/card/x-cards-list.html",
        "demo/declarative/index.html",
<<<<<<< HEAD
        "demo/doc/basic.html",
        "demo/doc/my-animatable.html",
        "demo/doc/my-dialog.html",
        "demo/doc/types.html",
=======
        "demo/doc/index.html",
        "demo/doc/my-animatable.html",
        "demo/doc/my-dialog.html",
>>>>>>> tensorflow/master
        "demo/dropdown/animated-dropdown.html",
        "demo/dropdown/index.html",
        "demo/grid/animated-grid.html",
        "demo/grid/fullsize-page-with-card.html",
        "demo/grid/index.html",
        "demo/list/full-view.html",
        "demo/list/index.html",
        "demo/list/list-demo.html",
        "demo/list/list-view.html",
        "demo/load/animated-grid.html",
        "demo/load/full-page.html",
        "demo/load/index.html",
        "demo/reprojection/animated-grid.html",
        "demo/reprojection/fullsize-page-with-card.html",
        "demo/reprojection/index.html",
        "demo/reprojection/reprojected-pages.html",
        "demo/tiles/circles-page.html",
        "demo/tiles/index.html",
        "demo/tiles/squares-page.html",
        "index.html",
        "neon-animatable.html",
        "neon-animatable-behavior.html",
        "neon-animated-pages.html",
        "neon-animation.html",
        "neon-animation-behavior.html",
        "neon-animation-runner-behavior.html",
        "neon-animations.html",
        "neon-shared-element-animatable-behavior.html",
        "neon-shared-element-animation-behavior.html",
        "web-animations.html",
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-a11y-keys-behavior",
    srcs = [
        "index.html",
        "iron-a11y-keys-behavior.html",
    ],
)

filegroup(
    name = "plottable",
    srcs = [
        "plottable.css",
        "plottable.js",
        "plottable.min.js",
    ],
)

filegroup(
    name = "webcomponentsjs",
    srcs = [
        "CustomElements.js",
        "CustomElements.min.js",
        "HTMLImports.js",
        "HTMLImports.min.js",
        "MutationObserver.js",
        "MutationObserver.min.js",
        "ShadowDOM.js",
        "ShadowDOM.min.js",
        "webcomponents.js",
        "webcomponents.min.js",
        "webcomponents-lite.js",
        "webcomponents-lite.min.js",
=======
    name = "paper_behaviors",
    srcs = [
        "index.html",
        "paper-button-behavior.html",
        "paper-checked-element-behavior.html",
        "paper-inky-focus-behavior.html",
        "paper-ripple-behavior.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-validatable-behavior",
    srcs = [
        "index.html",
        "iron-validatable-behavior.html",
=======
    name = "paper_button",
    srcs = [
        "index.html",
        "paper-button.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "sinon-chai",
    srcs = ["lib/sinon-chai.js"],
)

filegroup(
    name = "paper-button",
    srcs = [
        "index.html",
        "paper-button.html",
=======
    name = "paper_checkbox",
    srcs = [
        "index.html",
        "metadata.html",
        "paper-checkbox.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-input",
    srcs = [
        "index.html",
        "iron-input.html",
=======
    name = "paper_dropdown_menu",
    srcs = [
        "index.html",
        "paper-dropdown-menu.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-menu-behavior",
    srcs = [
        "index.html",
        "iron-menu-behavior.html",
        "iron-menubar-behavior.html",
=======
    name = "paper_header_panel",
    srcs = [
        "index.html",
        "paper-header-panel.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-slider",
    srcs = [
        "index.html",
        "paper-slider.html",
=======
    name = "paper_icon_button",
    srcs = [
        "index.html",
        "paper-icon-button.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-list",
    srcs = [
        "index.html",
        "iron-list.html",
        "test/smoke/avg-worst-case.html",
        "test/smoke/dummy-data.html",
        "test/smoke/index.html",
=======
    name = "paper_input",
    srcs = [
        "all-imports.html",
        "index.html",
        "paper-input.html",
        "paper-input-addon-behavior.html",
        "paper-input-behavior.html",
        "paper-input-char-counter.html",
        "paper-input-container.html",
        "paper-input-error.html",
        "paper-textarea.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "marked",
    srcs = [
        "Gulpfile.js",
        "index.js",
        "lib/marked.js",
        "marked.min.js",
=======
    name = "paper_item",
    srcs = [
        "all-imports.html",
        "index.html",
        "paper-icon-item.html",
        "paper-item.html",
        "paper-item-behavior.html",
        "paper-item-body.html",
        "paper-item-shared-styles.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-material",
    srcs = [
        "index.html",
        "paper-material.html",
=======
    name = "paper_material",
    srcs = [
        "index.html",
        "paper-material.html",
        "paper-material-shared-styles.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-range-behavior",
    srcs = [
        "index.html",
        "iron-range-behavior.html",
    ],
)

filegroup(
    name = "svg-typewriter",
    srcs = ["svgtypewriter.js"],
)

filegroup(
    name = "web-animations-js",
    srcs = [
        "web-animations.html",
        "web-animations.min.js",
        "web-animations-next.min.js",
        "web-animations-next-lite.min.js",
    ],
)

filegroup(
    name = "hydrolysis",
    srcs = [
        "hydrolysis.html",
        "hydrolysis.js",
        "hydrolysis-analyzer.html",
        "index.js",
    ],
)

filegroup(
    name = "web-component-tester",
    srcs = [
        "browser.js",
        "data/a11ySuite.js",
        "data/index.html",
=======
    name = "paper_menu",
    srcs = [
        "index.html",
        "paper-menu.html",
        "paper-menu-shared-styles.html",
        "paper-submenu.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-toggle-button",
    srcs = [
        "index.html",
        "paper-toggle-button.html",
=======
    name = "paper_menu_button",
    srcs = [
        "index.html",
        "paper-menu-button.html",
        "paper-menu-button-animations.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-behaviors",
    srcs = [
        "index.html",
        "paper-button-behavior.html",
        "paper-checked-element-behavior.html",
        "paper-inky-focus-behavior.html",
        "paper-ripple-behavior.html",
=======
    name = "paper_progress",
    srcs = [
        "index.html",
        "paper-progress.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-radio-group",
    srcs = [
        "index.html",
        "paper-radio-group.html",
=======
    name = "paper_radio_button",
    srcs = [
        "index.html",
        "paper-radio-button.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-selector",
    srcs = [
        "index.html",
        "iron-multi-selectable.html",
        "iron-selectable.html",
        "iron-selection.html",
        "iron-selector.html",
=======
    name = "paper_radio_group",
    srcs = [
        "index.html",
        "paper-radio-group.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-form-element-behavior",
    srcs = [
        "index.html",
        "iron-form-element-behavior.html",
    ],
)

filegroup(
    name = "mocha",
    srcs = [
        "mocha.css",
        "mocha.js",
    ],
)

filegroup(
    name = "dagre",
    srcs = [
        "dist/dagre.core.js",
        "dist/dagre.core.min.js",
=======
    name = "paper_ripple",
    srcs = [
        "index.html",
        "paper-ripple.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-behaviors",
    srcs = [
        "index.html",
        "iron-button-state.html",
        "iron-control-state.html",
    ],
)

filegroup(
    name = "graphlib",
    srcs = [
        "dist/graphlib.core.js",
        "dist/graphlib.core.min.js",
=======
    name = "paper_slider",
    srcs = [
        "index.html",
        "paper-slider.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-collapse",
    srcs = [
        "index.html",
        "iron-collapse.html",
=======
    name = "paper_styles",
    srcs = [
        "classes/global.html",
        "classes/shadow.html",
        "classes/shadow-layout.html",
        "classes/typography.html",
        "color.html",
        "default-theme.html",
        "demo.css",
        "demo-pages.html",
        "index.html",
        "paper-styles.html",
        "paper-styles-classes.html",
        "shadow.html",
        "typography.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-checkbox",
    srcs = [
        "index.html",
        "metadata.html",
        "paper-checkbox.html",
=======
    name = "paper_tabs",
    srcs = [
        "index.html",
        "paper-tab.html",
        "paper-tabs.html",
        "paper-tabs-icons.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-radio-button",
    srcs = [
        "index.html",
        "paper-radio-button.html",
=======
    name = "paper_toggle_button",
    srcs = [
        "index.html",
        "paper-toggle-button.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-header-panel",
    srcs = [
        "index.html",
        "paper-header-panel.css",
        "paper-header-panel.html",
    ],
)

filegroup(
    name = "prism-element",
    srcs = [
        "prism-highlighter.html",
        "prism-import.html",
=======
    name = "paper_toolbar",
    srcs = [
        "index.html",
        "paper-toolbar.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "chai",
    srcs = [
        "chai.js",
        "karma.conf.js",
        "karma.sauce.js",
        "sauce.browsers.js",
=======
    name = "plottable",
    srcs = [
        "plottable.css",
        "plottable.js",
        "plottable.min.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-menu-button",
    srcs = [
        "index.html",
        "paper-menu-button.html",
        "paper-menu-button-animations.html",
=======
    name = "polymer",
    srcs = [
        "polymer.html",
        "polymer-micro.html",
        "polymer-mini.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "polymer",
    srcs = [
        "polymer.html",
        "polymer-micro.html",
        "polymer-mini.html",
=======
    name = "promise_polyfill",
    srcs = [
        "Gruntfile.js",
        "Promise.js",
        "Promise.min.js",
        "Promise-Statics.js",
        "promise-polyfill.html",
        "promise-polyfill-lite.html",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "paper-ripple",
    srcs = [
        "index.html",
        "paper-ripple.html",
=======
    name = "web_animations_js",
    srcs = [
        "web-animations.html",
        "web-animations.min.js",
        "web-animations-next.min.js",
        "web-animations-next-lite.min.js",
>>>>>>> tensorflow/master
    ],
)

filegroup(
<<<<<<< HEAD
    name = "iron-iconset-svg",
    srcs = [
        "index.html",
        "iron-iconset-svg.html",
=======
    name = "webcomponentsjs",
    srcs = [
        "CustomElements.js",
        "CustomElements.min.js",
        "HTMLImports.js",
        "HTMLImports.min.js",
        "MutationObserver.js",
        "MutationObserver.min.js",
        "ShadowDOM.js",
        "ShadowDOM.min.js",
        "webcomponents.js",
        "webcomponents.min.js",
        "webcomponents-lite.js",
        "webcomponents-lite.min.js",
>>>>>>> tensorflow/master
    ],
)
